import java.io.IOException;                    // I/O exception from getWriter()
import java.io.PrintWriter;                    // Writes HTML characters to the browser
import jakarta.servlet.ServletException;       // Required on doGet signature (Tomcat 11)
import jakarta.servlet.http.HttpServlet;       // Parent class that understands HTTP
import jakarta.servlet.http.HttpServletRequest;  // Incoming request (URL, parameters)
import jakarta.servlet.http.HttpServletResponse; // Outgoing response (headers + body)

/** Practical 1: Hello Servlet — first dynamic HTML page from Java. */
public class HelloServlet extends HttpServlet {  // Tomcat loads this class by name

    private static final long serialVersionUID = 1L;  // Serializable version id

    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {     // Called on HTTP GET

        // Tell the browser the body is HTML (call BEFORE writing)
        response.setContentType("text/html");

        PrintWriter out = response.getWriter();          // Open the HTML writer
        out.println("<!DOCTYPE html>");                     // HTML5 document start
        out.println("<html>");                              // Root element
        out.println("<head><title>Hello Servlet</title></head>"); // Tab title
        out.println("<body>");                              // Visible page
        out.println("<h1>Welcome to Servlets</h1>");        // Dynamic heading
        out.println("<p>This page is generated by HelloServlet using doGet().</p>"); // Proof
        out.println("<p><a href='index.html#ex-hello'>Back to Index</a></p>"); // Link home
        out.println("</body>");                             // End body
        out.println("</html>");                             // End document

        System.out.println("[HelloServlet] doGet() executed successfully."); // Tomcat console only
    }
}
