import java.io.IOException;
import java.io.PrintWriter;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServlet;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

/**
 * Syllabus: Servlets Introduction, Need and Working
 */
public class ServletIntroWorking extends HttpServlet {

    private static final long serialVersionUID = 1L;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

        response.setContentType("text/html");
        PrintWriter out = response.getWriter();

        out.println("<!DOCTYPE html>");
        out.println("<html><head><meta charset='UTF-8'><title>Servlet Intro Need Working</title></head><body>");
        out.println("<h1>Servlets: Introduction, Need and Working</h1>");

        out.println("<h2>1) Introduction</h2>");
        out.println("<p>A <b>Servlet</b> is a Java class that runs on the server (Tomcat) and handles HTTP requests.</p>");
        out.println("<p>It generates dynamic response (HTML/JSON/text) for the browser.</p>");

        out.println("<h2>2) Need of Servlets</h2>");
        out.println("<ul>");
        out.println("<li>CGI was slow (new process per request).</li>");
        out.println("<li>Servlet uses thread per request - faster and scalable.</li>");
        out.println("<li>Platform independent (Java).</li>");
        out.println("<li>Good integration with Java EE APIs.</li>");
        out.println("</ul>");

        out.println("<h2>3) Working (Request Flow)</h2>");
        out.println("<ol>");
        out.println("<li>Browser sends HTTP request to Tomcat.</li>");
        out.println("<li>Tomcat finds servlet mapping from <code>web.xml</code>.</li>");
        out.println("<li>Container calls <b>service()</b> then <b>doGet()/doPost()</b>.</li>");
        out.println("<li>Servlet writes response using PrintWriter.</li>");
        out.println("<li>Browser shows the output.</li>");
        out.println("</ol>");

        out.println("<p><b>This page itself is generated by a Servlet</b> (ServletIntroWorking).</p>");
        out.println("<p><a href='index.html#ex-intro'>Back to Index</a></p>");
        out.println("</body></html>");
    }
}
